const answersFin = [
    "Kyllä, mene eteenpäin!",
    "Ei, se ei välttämättä ole paras idea.",
    "Se on sinun päätöksesi, mutta harkitse mahdollisia seurauksia.",
    "Jos se sopii arvoihisi ja tavoitteisiisi, mene eteenpäin.",
    "Se riippuu tilanteen yksityiskohdista.",
    "Se saattaisi olla syytä harkita muita vaihtoehtoja ensin.",
    "Se voisi olla hyvä tilaisuus, mutta varmista, että pohdit plussia ja miinuksia.",
    "Jos tunnet olosi varmaksi ja valmistautuneeksi, mene eteenpäin.",
    "Se voisi olla loistava päätös, mutta varmista, että sinulla on suunnitelma valmiina.",
    "Se ei välttämättä ole oikea valinta sinulle tällä hetkellä.",
    "Se voisi olla riskialtis liike, mutta mahdollinen palkinto voisi olla sen arvoinen.",
    "Lopulta se on sinun päätöksesi, mutta varmista, että pohdit asiaa huolellisesti.",
    "Jos se sopii pitkän aikavälin tavoitteisiisi, mene eteenpäin.",
    "Se voisi olla loistava tilaisuus, mutta valmistaudu haasteisiin, jotka saattavat tulla mukana.",
    "Se on sinun päätöksesi, mutta varmista, että sinulla on tarvittavat resurssit ja tuki.",
    "Jos se sopii arvoihisi ja uskomuksiisi, mene eteenpäin.",
    "Se voisi olla hyvä päätös, mutta varmista, että sinulla on varasuunnitelma, jos asiat eivät mene odotusten mukaisesti.",
    "Lopulta se on sinun päätöksesi, mutta harkitse mahdollisia riskejä ja palkintoja.",
    "Jos tunnet olosi innostuneeksi asiasta, mene eteenpäin.",
    "Se voisi olla loistava tilaisuus, mutta varmista, että sinulla on selkeä suunnitelma valmiina.",
    "Se on sinun päätöksesi, mutta harkitse mahdollista vaikutusta henkilökohtaiseen ja ammatilliseen elämääsi.",
    "Jos se sopii pitkän aikavälin tavoitteisiisi ja arvoihisi, mene eteenpäin.",
    "Se voisi olla hyvä päätös, mutta varmista, että sinulla on tarvittavat resurssit ja tuki.",
    "Lopulta se on sinun päätöksesi, mutta harkitse mahdollisia seurauksia.",
    "Se on sinun päätöksesi, mutta varmista, että sinulla on suunnitelma valmiina.",
    "Varmista, että ymmärrät tehtävän yksityiskohdat ennen päätöksen tekemistä.",
    "On tärkeää harkita mahdollista vaikutusta muihin ennen päätöksen tekemistä.",
    "Voisko olla hyvä idea saada toisen mielipide ennen päätöksen tekemistä?",
    "Mieti, miten tämä päätös vaikuttaa tulevaisuuden tavoitteisiisi ja suunnitelmiisi.",
    "On okay ottaa aikaa miettiä ennen päätöksen tekemistä.",
    "Varmista, että ymmärrät tämän päätöksen seuraukset ennen jatkamista.",
    "Harkitse mahdollisia riskejä ja palkintoja ennen päätöksen tekemistä.",
    "Voisko olla hyödyllistä neuvotella muiden kanssa, jotka ovat kokeneet samanlaisen tilanteen?",
    "Varmista, että sinulla on kaikki tarvittavat tiedot ennen päätöksen tekemistä.",
    "Mieti, miten tämä päätös sopii arvoihisi ja uskomuksiisi.",
    "On tärkeää harkita mahdollisia pitkän aikavälin vaikutuksia tästä päätöksestä.",
    "Mieti, miten tämä päätös sopii henkilökohtaisiin tavoitteisiisi ja arvoihisi.",
]